import 'package:meta/meta.dart';

/// Represents token usage information from an API response.
///
/// Contains the number of input and output tokens consumed by a request.
/// This information is included in every [Message] response from the API.
///
/// Example JSON:
/// ```json
/// {
///   "input_tokens": 25,
///   "output_tokens": 15
/// }
/// ```
@immutable
class Usage {
  /// The number of input tokens consumed by the request.
  final int inputTokens;

  /// The number of output tokens generated by the model.
  final int outputTokens;

  /// Creates a [Usage] instance with the given [inputTokens] and
  /// [outputTokens].
  const Usage({
    required this.inputTokens,
    required this.outputTokens,
  });

  /// Creates a [Usage] instance from a JSON map.
  ///
  /// Expects keys `input_tokens` and `output_tokens` in the JSON map.
  factory Usage.fromJson(Map<String, dynamic> json) {
    return Usage(
      inputTokens: json['input_tokens'] as int,
      outputTokens: json['output_tokens'] as int,
    );
  }

  /// Converts this [Usage] instance to a JSON map.
  ///
  /// Returns a map with keys `input_tokens` and `output_tokens`.
  Map<String, dynamic> toJson() {
    return {
      'input_tokens': inputTokens,
      'output_tokens': outputTokens,
    };
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is Usage &&
        other.inputTokens == inputTokens &&
        other.outputTokens == outputTokens;
  }

  @override
  int get hashCode => Object.hash(inputTokens, outputTokens);

  @override
  String toString() => 'Usage(inputTokens: $inputTokens, '
      'outputTokens: $outputTokens)';
}
